dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
    - "7.3"
    - "7.2"
    - "7.1"
    - "nightly"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.7.0
  - CONTAO_VERSION=contao/core-bundle ~4.6.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0
  - CONTAO_VERSION=contao/core-bundle ~4.4.0

before_install:
    - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer require $CONTAO_VERSION --no-update
    - travis_retry composer update --prefer-dist --dev --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
